# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, required to find the models/env.py
# when running alembic from outside the project dir
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# limit the conversion of database types to the specified format
# version_locations = %(here)s/bar:%(here)s/bat

# logging configuration is at the end of the file.

[post_write_hooks]

[logging]
default = INFO

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
